# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            HPC Training
tagline:          '-Alex Pacheco'
description:      'Slides for my presentations at HPC Training sessions'
url:              http://www.alexpacheco.net
baseurl:          /hpc-training

author:
  name:           'Alex Pacheco'
  url:            http://www.alexpacheco.net

# Custom vars
version:          

github:
  repo:           https://github.com/alexpacheco/hpc-training
  home:           https://github.com/alexpacheco
